provider:
  name: faas
  gateway: http://127.0.0.1:8080
functions:
  leaderboard:
    lang: golang-middleware
    handler: ./leaderboard
    image: leaderboard:latest
    environment:
      postgres_db: defaultdb
      postgres_sslmode: require
      postgres_port: 25060
    secrets:
      - leaderboard-app-secrets

  github-sub:
    lang: golang-middleware
    handler: ./github-sub
    image: github-sub:latest
    environment:
      postgres_db: defaultdb
      postgres_sslmode: require
      postgres_port: 25060
    secrets:
      - leaderboard-app-secrets
